import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import QuerysProvider from "./QueryProvider";
import { StoreProvider } from "./StoreProvider";

const SoraFont = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Me Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${SoraFont.variable} antialiased`}>
        <QuerysProvider>
          <StoreProvider>{children}</StoreProvider>
        </QuerysProvider>
      </body>
    </html>
  );
}
